substitutions:
  device: "misk-bedroom"
  spray_pin: "D8"
  interval1: "5"
  interval2: "15"
  interval3: "30"
  interval4: "60"
  interval5: "120"
  squirt_pulse: "150ms"
  maxSquirts: "2500"

packages:
  misk: !include common/misk.yaml
